# Generated by Django 2.0.4 on 2018-05-28 19:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('id_deck', models.PositiveIntegerField(db_index=True)),
                ('token', models.PositiveIntegerField(choices=[(0, 'joker'), (1, 'token_A'), (3, 'token_B'), (3, 'token_C'), (2, 'token_D'), (1, 'token_E'), (4, 'token_F'), (2, 'token_G'), (4, 'token_H'), (1, 'token_I'), (8, 'token_J'), (10, 'token_K'), (1, 'token_L'), (2, 'token_M'), (1, 'token_N'), (1, 'token_O'), (3, 'token_P'), (8, 'token_Q'), (1, 'token_R'), (1, 'token_S'), (1, 'token_T'), (1, 'token_U'), (4, 'token_V'), (10, 'token_W'), (10, 'token_X'), (10, 'token_Y'), (10, 'token_Z')])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_game', models.AutoField(primary_key=True, serialize=False)),
                ('id_deck', models.PositiveIntegerField()),
                ('hand_player_1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'joker'), (1, 'token_A'), (3, 'token_B'), (3, 'token_C'), (2, 'token_D'), (1, 'token_E'), (4, 'token_F'), (2, 'token_G'), (4, 'token_H'), (1, 'token_I'), (8, 'token_J'), (10, 'token_K'), (1, 'token_L'), (2, 'token_M'), (1, 'token_N'), (1, 'token_O'), (3, 'token_P'), (8, 'token_Q'), (1, 'token_R'), (1, 'token_S'), (1, 'token_T'), (1, 'token_U'), (4, 'token_V'), (10, 'token_W'), (10, 'token_X'), (10, 'token_Y'), (10, 'token_Z')], max_length=7), size=7)),
                ('hand_player_2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'joker'), (1, 'token_A'), (3, 'token_B'), (3, 'token_C'), (2, 'token_D'), (1, 'token_E'), (4, 'token_F'), (2, 'token_G'), (4, 'token_H'), (1, 'token_I'), (8, 'token_J'), (10, 'token_K'), (1, 'token_L'), (2, 'token_M'), (1, 'token_N'), (1, 'token_O'), (3, 'token_P'), (8, 'token_Q'), (1, 'token_R'), (1, 'token_S'), (1, 'token_T'), (1, 'token_U'), (4, 'token_V'), (10, 'token_W'), (10, 'token_X'), (10, 'token_Y'), (10, 'token_Z')], max_length=7), size=7)),
                ('gameboard', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'joker'), (1, 'token_A'), (3, 'token_B'), (3, 'token_C'), (2, 'token_D'), (1, 'token_E'), (4, 'token_F'), (2, 'token_G'), (4, 'token_H'), (1, 'token_I'), (8, 'token_J'), (10, 'token_K'), (1, 'token_L'), (2, 'token_M'), (1, 'token_N'), (1, 'token_O'), (3, 'token_P'), (8, 'token_Q'), (1, 'token_R'), (1, 'token_S'), (1, 'token_T'), (1, 'token_U'), (4, 'token_V'), (10, 'token_W'), (10, 'token_X'), (10, 'token_Y'), (10, 'token_Z')], max_length=7), size=15), size=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrabble.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrabble_game_related', to='scrabble.Player'),
        ),
    ]
