# Generated by Django 2.0.4 on 2018-05-28 19:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('ID_token', models.AutoField(primary_key=True, serialize=False)),
                ('ID_deck', models.PositiveIntegerField(db_index=True)),
                ('token', models.PositiveIntegerField(choices=[(0, 'JOKER'), (1, 'Token_A'), (3, 'Token_B'), (2, 'Token_D'), (4, 'Token_F'), (8, 'Token_J'), (10, 'Token_K')])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('ID_game', models.AutoField(primary_key=True, serialize=False)),
                ('ID_deck', models.PositiveIntegerField()),
                ('Hand_player_1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'JOKER'), (1, 'Token_A'), (3, 'Token_B'), (2, 'Token_D'), (4, 'Token_F'), (8, 'Token_J'), (10, 'Token_K')], max_length=7), size=7)),
                ('Hand_player_2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'JOKER'), (1, 'Token_A'), (3, 'Token_B'), (2, 'Token_D'), (4, 'Token_F'), (8, 'Token_J'), (10, 'Token_K')], max_length=7), size=7)),
                ('GameBoard', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'JOKER'), (1, 'Token_A'), (3, 'Token_B'), (2, 'Token_D'), (4, 'Token_F'), (8, 'Token_J'), (10, 'Token_K')], max_length=7), size=15), size=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ID_player', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrabble.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='Player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrabble_game_related', to='scrabble.Player'),
        ),
    ]
