sudo: required
language: python
python:
  - "3.6.3"
services:
  - postgresql
addons:
  postgresql: "10.3"
install:
  - sudo apt-get update
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database default;' -U postgres
script:
  - python manage.py test
