language: python
python:
  - "3.6.3"
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - export PATH_TO_MANAGE="$(dirname "$(find . -type f -name 'manage.py')")"
  - cd $PATH_TO_MANAGE
  - python manage.py test
