sudo: required
language: python
python:
    - "3.6.3"
services:
    - postgresql
addons:
  postgresql: "9.6"
install:
  - sudo apt-get update
  - pip install -r requirements/travis.txt
script:
  - export DJANGO_SETTINGS_MODULE=mysitedj2_0.settings.travis
  - export PATH_TO_MANAGE="$(dirname "$(find . -type f -name 'manage.py')")"
  - cd $PATH_TO_MANAGE
  - python manage.py test --settings==mysitedj2_0.settings.travis
