# Generated by Django 2.0.4 on 2018-05-07 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Code postal')),
                ('gender', models.CharField(max_length=255, verbose_name='Civilite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
